### ISSUE TITLE
ALOT of TV Shows not playing 

### ISSUE THREAD

**Issue by Uokereh** [OstlerDev/PopcornTV#100] opened 2015-07-12 04:43 UTC
is anyone else having this problem, select a TV show, any show and episode and click play, Terminal will attempt to start streaming but will stop without playing selected episode. This is happening with ALOT of the shows on PopcornTV. - any fix out there?

**Comment by OstlerDev** [comment] 2015-07-12 04:46
If you take a look in the log you can clearly see that it attempts to convert the unsupported video using FFMPEG. That feature does not fully work yet. 

This could also be caused by you having a low download speed.

**Comment by Uokereh** [comment] 2015-07-12 04:51
can't be download speed because i have success streaming with a few tv shows, very few.

**Comment by masonjames** [comment] 2015-07-12 05:18
Hiya @Uokereh, try running the app in 'debug' mode and posting a log with the errors you're getting.

Please read here for more on posting an issue: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

If the episodes aren't in mp4 format the appletv can't play them.  Experimental support for converting videos on the fly has just been added earlier today using FFMPEG as @OstlerDev mentioned.  I've had a pretty positive experience with it so far, but your mileage will definitely vary.

If you post a gist with your log file we can take a look at the specific error messages you're seeing.  Thanks!

**Comment by JakeRound** [comment] 2015-07-12 13:20
While I know this feature is still in early development, I've had similar issues. For an example the show will download and pass 12mb fairly quickly (within a few seconds) attempt to play the stream with the spinning cuticle spinner and output an error and end the current stream. While this isn't for ever show it does happen with shows such as Family Guy, Simpsons etc.

I can post a error log as soon as I'm home.

**Comment by OstlerDev** [comment] 2015-07-12 22:17
This seems to be an issue where it might not be converting to a supported format, I am seeing that it is working on converting the video but then will crash when it attempts to serve it to the Apple TV. 

I am looking into this now, but will close this issue and append the log to #3

**Closed by OstlerDev** 2015-07-12 22:17 UTC

**Comment by OstlerDev** [comment] 2015-07-12 22:36
@Uokereh @JakeRound Do either of you have specific episodes that you are able to repeat this with?

**Comment by JakeRound** [comment] 2015-07-12 23:31
Family Guy Season 13 Episode 18 seems to reproduce this issue every time, apologies for the late reply.

**Comment by JakeRound** [comment] 2015-07-12 23:38
@OstlerDev Error log, torrent downloads starts to convert but for some reason the stream is forced to end. https://gist.github.com/JakeRound/27133ff78a2ff9cbe592

**Comment by OstlerDev** [comment] 2015-07-12 23:39
That is the episode I have been testing it on, I am pushing up an update soon that will fix most issues, however it does seem that file is corrupt. The update I am pushing up will also speedup conversions for some.

Please pull down the latest version and try again.

**Comment by JakeRound** [comment] 2015-07-12 23:42
Okay thanks! I'll let you know how it goes.

**Comment by OstlerDev** [comment] 2015-07-12 23:43
No problem. Thanks for testing!
