### ISSUE TITLE
Fanart on, nothing work

### ISSUE THREAD

**Issue by NicoMag** [OstlerDev/PopcornTV#67] opened 2015-06-26 08:34 UTC
Hello
I have a non-jailbroken ATV with last version 7.2 (7512) software on. But when I put "fanart on", the movie page doesn't load (I tried a lot of different movies). The wheel is loading, loading, loading... and then suddenly "trailers are not available. try again later" on the screen.

Oh and it's working with TV Shows. Only movies seems affected. 

Popcorn TV.log : http://pastebin.com/WtPawW1r
ATVSettings : http://pastebin.com/pbe9eKxQ

**Comment by OstlerDev** [comment] 2015-06-26 08:40
I am able to reproduce this issue, I am looking into it now and will push up an update as soon as I can.

**Comment by OstlerDev** [comment] 2015-06-26 08:46
Turns out that this error occurs because I modified the fanart generator in a recent patch adding extra variables to the callback function when there should have just been one. ( https://github.com/OstlerDev/PopcornTV/commit/9d728a7c48900083405fc5ad80272e1ede633be6#diff-843efcd5b510cd02c353d562259250a9R24 )

This is fixed in the commit I am pushing up now.

**Comment by OstlerDev** [comment] 2015-06-26 08:47
@NicoMag Please download the latest version and confirm that this works for you.

**Closed** 2015-06-26 08:47 UTC
Labels: bug, confirmed

**Comment by NicoMag** [comment] 2015-06-26 09:36
Perfect ! Works amazing, beautiful look ! Once again great work

**Comment by OstlerDev** [comment] 2015-06-26 09:37
No problem! Enjoy!
