### ISSUE TITLE
Stuck in Converting File, Command prompt keeps saying progress.json

### ISSUE THREAD

**Issue by mmmpires** [OstlerDev/PopcornTV#230] opened 2015-09-13 09:48 UTC
Hi, congratulations for the effort put in these developments and for answering all our bugs.

I saw other bugs related to this but none solve my problem and I believe mine is different from the others I read.

Sorry for the trouble :-(

I installed this great app yesterday.

I can watch movies and some Series.

But other series I cannot (game of thrones, Breaking bad).

It gets stuck in Converting File, Command prompt keeps saying progress.json.

I've installed ffmped.exe in the PopocornTV folder.

Here are the command window prompts:
DNS: xp.apple.com
DNS: itunes.apple.com
DNS: bookkeeper.itunes.apple.com
DNS: p20-buy.itunes.apple.com
DNS: se.itunes.apple.com
DNS: a2.mzstatic.com
Web: SSL: js/application.js
Web: templates/navbar.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: templates/index.xml
DNS: init-p01st.push.apple.com
Web: /js/utils.js
DNS: 19-courier.push.apple.com
DNS: p04-streams.icloud.com
DNS: p04-sharedstreams.icloud.com
Web: /Parade.xml
DNS: s.ynet.io
Web: /Parade.xml
DNS: walter.trakt.us
DNS: www.apple.com
Web: /Parade.xml
Web: /Parade.xml
Web: /Parade.xml
DNS: configuration.apple.com
DNS: pd-nk.itunes.apple.com
Web: templates/TVNav.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: /TVGrid.xml
Web: /js/utils.js
Web: /seasons.xml
DNS: e673.e9.akamaiedge.net
DNS: play.itunes.apple.com
Web: /episodes.xml
Web: /js/utils.js
Web: /TVPrePlay.xml
Web: /js/utils.js
Web: /thumbnails/MediaBadges/480p.png
Web: /thumbnails/MediaBadges/480p.png
Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Web: /js/play.js
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Streamer: Ready to Stream, binding to http://192.168.1.66:6105
warning: =============== WARNING ===============
warning: Attempting to convert non-supported file using FFMPEG.
warning: This is VERY Unstable and most likely WILL NOT WORK!
warning: =======================================
error: uncaughtException: Path must be a string. Received undefined
{ date: 'Sun Sep 13 2015 09:23:20 GMT+0100 (Hora de Verão de GMT)',
  process:
   { pid: 3488,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\Mário\\Desktop\\PopcornTV',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v4.0.0',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\Users\\Mário\\Desktop\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 82821120, heapTotal: 41205248, heapUsed: 27513888 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 1759.4546754 },
  trace:
   [ { column: 11,
       file: 'path.js',
       function: 'assertPath',
       line: 8,
       method: null,
       native: false },
     { column: 5,
       file: 'path.js',
       function: 'Object.win32.join',
       line: 221,
       method: 'win32.join',
       native: false },
     { column: 22,
       file: 'C:\\Users\\Mário\\Desktop\\PopcornTV\\webserver.js',
       function: 'convertFile',
       line: 746,
       method: null,
       native: false },
     { column: 11,
       file: 'C:\\Users\\Mário\\Desktop\\PopcornTV\\webserver.js',
       function: '',
       line: 90,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'emitOne',
       line: 82,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'emit',
       line: 169,
       method: null,
       native: false },
     { column: 22,
       file: 'C:\\Users\\Mário\\Desktop\\PopcornTV\\streamer-server.js',
       function: '',
       line: 65,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 77,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'TorrentStreamer.emit',
       line: 169,
       method: 'emit',
       native: false },
     { column: 8,
       file: 'C:\\Users\\Mário\\Desktop\\PopcornTV\\lib\\streamers\\base.js',
       function: '',
       line: 60,
       method: null,
       native: false } ],
  stack:
   [ 'TypeError: Path must be a string. Received undefined',
     '    at assertPath (path.js:8:11)',
     '    at Object.win32.join (path.js:221:5)',
     '    at convertFile (C:\\Users\\Mário\\Desktop\\PopcornTV\\webserver.js:746
:22)',
     '    at null.<anonymous> (C:\\Users\\Mário\\Desktop\\PopcornTV\\webserver.j
s:90:11)',
     '    at emitOne (events.js:82:20)',
     '    at emit (events.js:169:7)',
     '    at TorrentStreamer.<anonymous> (C:\\Users\\Mário\\Desktop\\PopcornTV\\
streamer-server.js:65:22)',
     '    at emitOne (events.js:77:13)',
     '    at TorrentStreamer.emit (events.js:169:7)',
     '    at Through2.<anonymous> (C:\\Users\\Mário\\Desktop\\PopcornTV\\lib\\st
reamers\\base.js:60:8)' ] }
error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at convertFile (C:\Users\Mário\Desktop\PopcornTV\webserver.js:746:22)
    at null.<anonymous> (C:\Users\Mário\Desktop\PopcornTV\webserver.js:90:11)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at TorrentStreamer.<anonymous> (C:\Users\Mário\Desktop\PopcornTV\streamer-se
rver.js:65:22)
    at emitOne (events.js:77:13)
    at TorrentStreamer.emit (events.js:169:7)
    at Through2.<anonymous> (C:\Users\Mário\Desktop\PopcornTV\lib\streamers\base
.js:60:8)
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
DNS: itunes.apple.com.edgekey.net
Web: /progress.json
DNS: upp.itunes.apple.com
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json

Again - great work for the community!

**Comment by OstlerDev** [comment] 2015-09-21 15:28
Not really sure why that happened, but the feature is in beta and is not too stable :/

**Comment by OstlerDev** [comment] 2015-09-21 15:31
Duplicate of #229

**Closed by OstlerDev** 2015-09-21 15:31 UTC
