### ISSUE TITLE
Booted when trying to play TV shows

### ISSUE THREAD

**Issue by Moeith** [OstlerDev/PopcornTV#41] opened 2015-06-15 02:34 UTC
Not sure if the TV shows are working yet. I thought I would just double check. Here is the code I'm getting:

Error: ENOENT, no such file or directory './aTVSettings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.checkSetting (/Users/dfDerikBW/Desktop/PopcornTV/settings.js:134:19)
    at null.<anonymous> (/Users/dfDerikBW/Desktop/PopcornTV/webserver.js:61:34)
    at emit (events.js:129:20)
    at null._onTimeout (/Users/dfDerikBW/Desktop/PopcornTV/streamer-server.js:100:18)
    at Timer.listOnTimeout (timers.js:110:15)

I then get booted out.

**Comment by OstlerDev** [comment] 2015-06-15 02:47
This is a duplicate of #40 I just pushed up a commit that should solve this issue, can you please attempt to update to the latest and replicate the issue?

**Closed by OstlerDev** 2015-06-15 02:47 UTC
Labels: duplicate
