### ISSUE TITLE
After watching a movie, server disconnects itself. 

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#76] opened 2015-07-01 21:34 UTC
So after finishing this movie, i was going to play another movie. but it was stuck on "accessing trailers" screen. When i checked my computer, there was nothing going on. so i had to run popcorntv again.
here's the log. http://pastebin.com/PUDrgRxY

**Comment by OstlerDev** [comment] 2015-07-01 21:36
This seems to be an issue with Windows, on the settings page of PopcornTV change the "Keep Movie Downloads" to "On". This will fix the issue until I can push up a patch.

**Comment by Mehmeed** [comment] 2015-07-01 21:40
Alrighty thanks

**Comment by OstlerDev** [comment] 2015-07-02 01:10
Duplicate of #70

**Closed by OstlerDev** 2015-07-02 01:10 UTC
