### ISSUE TITLE
Unable to access anything under movies after commit 7979231cf1e9e64845e57cc8521e6f1cf39816ec

### ISSUE THREAD

**Issue by seeitbelieveit** [OstlerDev/PopcornTV#63] opened 2015-06-25 06:24 UTC
https://gist.github.com/seeitbelieveit/06c0b85664b2526553e4

**Comment by seeitbelieveit** [comment] 2015-06-25 10:37
Fixed with a fresh clone, unsure of what actual issue was.

**Comment by seeitbelieveit** [comment] 2015-06-25 10:39
Issue returns with second selection of movie title

**Comment by OstlerDev** [comment] 2015-06-25 10:47
What movies are you selecting?

**Comment by seeitbelieveit** [comment] 2015-06-25 10:49
Recently Added>Maggie

Now unable to even access maggie again

**Comment by OstlerDev** [comment] 2015-06-25 10:50
I will test it in the morning.

**Comment by seeitbelieveit** [comment] 2015-06-25 10:51
This is on OS X Yosemite also

**Comment by OstlerDev** [comment] 2015-06-25 21:40
Could be a posible duplicate of #15 please pull down the latest and try again.

**Comment by OstlerDev** [comment] 2015-06-25 21:42
Fixed in commit 2ac3a94d11090e7e7eaa7de0d5672e089570cf6e

**Closed by OstlerDev** 2015-06-25 21:42 UTC

**Comment by seeitbelieveit** [comment] 2015-06-27 01:59
yeah its fixed, thanks
