### ISSUE TITLE
Download Movie Again after download>watch>delete

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#79] opened 2015-07-05 14:54 UTC
Running latest version from trunk.  PopcornTV is working great on new movies.

I had previously downloaded watched a movie w/ settings for "keep" to "on". 

I manually deleted the film in Finder.

I attempted to watch the movie again, but it never goes past 0% downloaded.

Full log file shows movie not downloading, second movie (not previously downloaded) working, then going back to original repeats behavior:
`2015-07-05T14:45:19.557Z - Debug: [0%] Downloaded 0.02MB - 0.01MB/s | Peers: 0 Seeds: 0 | ETA: 1400m`

I never get past that line, but only for the movie that I've previously downloaded and manually deleted.
https://gist.github.com/masonjames/b4a8acb86c1f16e60e1f (full log)

Edit possibly related to issue #50

**Comment by OstlerDev** [comment] 2015-07-05 17:52
Can you reproduce this on multiple movies?

Also, the files you needed to delete can be found at "assets/torrent-stream/" that is where the actual torrent is downloaded to, it is then renamed and streamed to the file inside the main folder.

Were you just deleting the MP4 inside the main folder and not the torrent-stream folder as well?

**Comment by OstlerDev** [comment] 2015-07-06 06:04
I am going to close this for now as I believe the error you were having might have been because you did not delete the actual torrent file. If it is not resolved, feel free to reopen the issue.

**Closed** 2015-07-06 06:05 UTC

**Comment by masonjames** [comment] 2015-07-08 03:24
sorry it's been a few days now.  been very busy.

You're right - deleting the assets/torrent-stream/ files enabled me to re-download the movie and watch it without any issues. Thanks!

**Comment by OstlerDev** [comment] 2015-07-08 03:29
Your fine, thanks for responding!
