### ISSUE TITLE
DNS Server over network

### ISSUE THREAD

**Issue by MatthieuTnsc** [OstlerDev/PopcornTV#220] opened 2015-09-04 08:38 UTC
Hi, I am trying to install PopcornTV on my personal server and reach it over the network ip.
I tried to change the LOCAL_IP constant inside atv.js (:22) with my network IP, but when it starts the DNS I get the following error :

    ========= FATAL ERROR =========
    Cannot start DNS Server. Please make sure you are using the correct IP!
    Error Code: EADDRNOTAVAIL
    ===============================

Is there a simple way to do it ? I'm not really a "network guy"

**Comment by domidyon** [comment] 2015-09-05 16:36
I am having the same problem, any fix for this?

**Comment by masonjames** [comment] 2015-09-05 22:03
I have PopcornTV running on my raspberry pi.  Just make sure your IP is defined correctly in config.json and use the IP address in your apple tv settings.
ie instead of this:
`http://trailers.apple.com/trailers.cer`
use this:
`http://127.0.0.1/trailers.cer`

I didn't need to change anything in atv.js. The rest of the setup was as normal.  I have to ssh into the raspberry pi and run it w/ sudo though. Otherwise I get an error.

**Comment by OstlerDev** [comment] 2015-09-06 01:54
@MatthieuTnsc @domidyon Please post your `config.json` file so that I can take a look at it.

**Comment by OstlerDev** [comment] 2015-09-12 17:17
@MatthieuTnsc @domidyon Are you still having issues?

**Comment by idanew** [comment] 2015-10-04 19:13
hi i have the same error
tried : http://127.0.0.1/trailers.cer
and gets in ate: unable to add profile, error occurred [-1004]

**Comment by khushkaran** [comment] 2015-10-04 19:16
@idanew: 127.0.0.1 is localhost, if you are on a mac, do this, open terminal and type `ifconfig | grep -i "inet 192"` and copy the ip address after the word "inet"

**Comment by pmoricz** [comment] 2015-10-05 06:21
Hi! I'm sorry guys, but I'm really not a very advanced in all this. I have a router, which is connected to my modem, and also a powerline adapter. On the room where I have the ATV the other adapter is connected.
What I don't understand is where the problem is. I tried changing the adress on config.json for my ip address (which I looked up on whatsmyip.com). It's definitely not the same one I have on my network which is assigned to me by my router 192.168... et etc. I also see, all these addresses change all the time since they are dynamic.. So i'm really lost on which ip adress to use. Also when I try to create the profile on my apple tv I get an error saying it was impossible to create the profile. So I'm really lost on how to set this up. Can someone help me out? Thanks a lot!

**Closed** 2015-10-05 06:27 UTC

**Comment by OstlerDev** [comment] 2015-10-05 06:29
Hey there! So you should be using your local IP address (the one that starts with 192 or 10). The one you looked up is your public IP and would not work without further configuration.

I suggest just deleting your config.json file and starting PopcornTV back up, it will generate a new config with the correct IP.

**Comment by pmoricz** [comment] 2015-10-05 07:17
Hey! I did all this, and fortunately I got to set it up correctly! thanks a lot! But now, when I try to load a movie it just stays at Accessing trailers, and then it says it's not available. Why can this be happening? Is there any info or file I can share with you to make the reasons of my problem clearer to you? Thanks for the help so far. I hope I'm not posting this at the wrong place now.
