### ISSUE TITLE
Fix subtitles display on 3D movies

### ISSUE THREAD

**Issue by pitercio** [OstlerDev/PopcornTV#214] opened 2015-09-01 15:54 UTC
Hi,

I have just noticed that I posted this on the PopcornTV-App instead... Let me repost it here :)

Yesterday I tried to watch the 3D version of "Mad Max" movie and I noticed that, currently, the subtitles are shown in the middle of side-by-side images, so when the TV switches to 3D-mode, the subtitles split by the middle and become unreadable. The screen looks like this:

![img_6774](https://cloud.githubusercontent.com/assets/3392628/9609144/5f5c1afc-50d2-11e5-8271-bde3fb54ed7d.JPG)

(the actual subtitle said "Mi mundo es fuego y sangre")

Could it be possible to render the subtitles twice, side-by-side, just like the movie, so when "joining" both sides they were readable?

Thank you in advance!!

**Comment by OstlerDev** [comment] 2015-09-01 18:31
Duplicate of #174

**Closed by OstlerDev** 2015-09-01 18:31 UTC
